"use client";
import { Provider } from "react-redux";
import { store } from "./store";
import "./globals.css";
import { Metadata } from "next";

const metadata: Metadata = {
  title: "Drawing App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <head className="text-base leading-7 text-gray-900"></head>
      <body>
        <Provider store={store}>{children}</Provider>
      </body>
    </html>
  );
}
