import { Provider } from 'react-redux'
import { store } from './store'
import './globals.css'
import { Metadata } from 'next';




export const metadata: Metadata = {
  title: 'Drawing App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <Provider store={store}>
      {children}
    </Provider>
  )
}
